import {NextResponse} from 'next/server';
import {z} from 'zod';
import {NotificationType} from '@prisma/client';
import {requireAdmin} from '@/lib/auth';
import {db} from '@/lib/db';
import {createNotification} from '@/lib/notifications';
const schema=z.object({userId:z.string(),status:z.enum(['ACTIVE','FROZEN']).optional(),role:z.enum(['USER','ADMIN']).optional(),kycStatus:z.enum(['PENDING','APPROVED','REJECTED','NEEDS_CHANGES']).optional()});
export async function GET(){try{await requireAdmin();return NextResponse.json(await db.user.findMany({select:{id:true,email:true,name:true,role:true,status:true,kycStatus:true,accountMode:true,createdAt:true},orderBy:{createdAt:'desc'},take:200}));}catch{return NextResponse.json({error:'Forbidden'},{status:403})}}
export async function PATCH(req:Request){try{const admin=await requireAdmin();const p=schema.parse(await req.json());if(p.userId===admin.id&&(p.status==='FROZEN'||p.role==='USER'))throw new Error('CANNOT_DISABLE_CURRENT_ADMIN');const u=await db.$transaction(async tx=>{const current=await tx.user.findUniqueOrThrow({where:{id:p.userId},select:{kycStatus:true}});const updated=await tx.user.update({where:{id:p.userId},data:{status:p.status,role:p.role,kycStatus:p.kycStatus},select:{id:true,email:true,name:true,role:true,status:true,kycStatus:true,accountMode:true,createdAt:true}});await tx.auditLog.create({data:{actorId:admin.id,action:'USER_UPDATE',entity:'USER',entityId:updated.id,metadata:p}});if(p.kycStatus&&p.kycStatus!==current.kycStatus){const title=p.kycStatus==='APPROVED'?'Identity verification approved':p.kycStatus==='REJECTED'?'Identity verification rejected':p.kycStatus==='NEEDS_CHANGES'?'Additional verification required':'Identity verification status updated';const message=p.kycStatus==='NEEDS_CHANGES'?'An administrator requested additional identity information. Review the Verification page.':`Your identity verification status is ${p.kycStatus.toLowerCase().replaceAll('_',' ')}.`;await createNotification(tx,{userId:updated.id,type:NotificationType.KYC,title,message,dedupeKey:`kyc:${updated.id}:${p.kycStatus}:${new Date().toISOString()}`,actionUrl:'/kyc'});}return updated});return NextResponse.json(u);}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Invalid request'},{status:400})}}
